name: 'Install a Visual Studio Extension' 
description: 'Download the latest extension version and install in Visual Studio'
inputs:
  packagename: 
    description:  'Package names from the Visual Studio Marketplace URL itemName parameter'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - id: vsix
      shell: pwsh
      run: |
        Write-Output ${{ inputs.packagename }}
        Write-Output ${{ inputs.packagename }}
        Write-Output ${{ inputs.packagename }}
        Write-Output ${{ inputs.packagename }}