name: Example Build

on:
  push:
    branches:
    - main
    paths: 
      - '**'
      - '!.editorconfig'
      - '!.gitattributes'
      - '!.gitignore'
      - '!*.md'
      - '!LICENSE'
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  
jobs: 
  Build:
    name: Example Action  
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.2    

    - name: Setup nuget
      uses: nuget/setup-nuget@v1
    
    - name: Install Visual Studio Extension
      uses: microcompiler/install-vsix@v1
